# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "srs"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = [
  "Luis Daniel Casais <https://github.com/rajayonin>",
  "José Antonio Verde <https://github.com/joseaverde>",
  "Álvaro Guerrero <https://github.com/ALVAROPING1>"
]
license = "Unlicense"
description = "Support for Software Requirements Specification in Typst."
homepage = "https://typst.app/universe/package/srs"
repository = "https://github.com/rajayonin/srs-typst"
keywords = []
categories = []
disciplines = []
# compiler = ""
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
